-- Verify Seed Data Persistence
-- Run this script against the banking_system database to check if seed users and accounts exist

SELECT 'CUSTOMER TABLE' AS verification;
SELECT CUSTOMER_ID, EMAIL, CUSTOMER_NAME, ROLE, APPROVED FROM CUSTOMER ORDER BY CUSTOMER_ID;

SELECT '' AS blank;
SELECT 'ACCOUNT TABLE' AS verification;
SELECT ACCOUNT_NUMBER, ACCOUNT_TYPE, CUSTOMER_ID, BALANCE, DATE_OPENED FROM ACCOUNT ORDER BY ACCOUNT_NUMBER;

SELECT '' AS blank;
SELECT 'ACCOUNT COUNT BY CUSTOMER' AS verification;
SELECT 
    c.CUSTOMER_ID, 
    c.EMAIL, 
    COUNT(a.ACCOUNT_NUMBER) as account_count
FROM CUSTOMER c
LEFT JOIN ACCOUNT a ON c.CUSTOMER_ID = a.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.EMAIL
ORDER BY c.CUSTOMER_ID;

SELECT '' AS blank;
SELECT 'TRANSACTION TABLE' AS verification;
SELECT TRANSACTION_ID, ACCOUNT_NUMBER, TRANSACTION_TYPE, AMOUNT, TRANSACTION_DATE FROM "TRANSACTION" ORDER BY TRANSACTION_DATE DESC FETCH FIRST 10 ROWS ONLY;
