-- Create Database
CREATE DATABASE IF NOT EXISTS banking_system;
USE banking_system;

-- CUSTOMER Table
CREATE TABLE IF NOT EXISTS CUSTOMER (
    CUSTOMER_ID VARCHAR(50) PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    SURNAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD_HASH VARCHAR(255),
    ROLE VARCHAR(20) DEFAULT 'CUSTOMER',
    APPROVED INT DEFAULT 1,
    SUSPENDED INT DEFAULT 0,
    DATE_OF_BIRTH DATE,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ACCOUNT Table
CREATE TABLE IF NOT EXISTS ACCOUNT (
    ACCOUNT_NUMBER VARCHAR(50) PRIMARY KEY,
    ACCOUNT_TYPE VARCHAR(20) NOT NULL,
    BALANCE DOUBLE NOT NULL DEFAULT 0.0,
    BRANCH VARCHAR(100) NOT NULL,
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    DATE_OPENED DATE NOT NULL,
    LAST_INTEREST_DATE DATE,
    EMPLOYER VARCHAR(100),
    EMPLOYER_ADDRESS VARCHAR(255),
    INTEREST_RATE DOUBLE,
    MINIMUM_BALANCE DOUBLE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TRANSACTION Table
CREATE TABLE IF NOT EXISTS TRANSACTION (
    TRANSACTION_ID VARCHAR(50) PRIMARY KEY,
    TRANSACTION_TYPE VARCHAR(20) NOT NULL,
    AMOUNT DOUBLE NOT NULL,
    TRANSACTION_DATE DATE NOT NULL,
    ACCOUNT_NUMBER VARCHAR(50) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ACCOUNT_NUMBER) REFERENCES ACCOUNT(ACCOUNT_NUMBER)
);

-- Create Indexes for better performance
CREATE INDEX idx_customer_id ON ACCOUNT(CUSTOMER_ID);
CREATE INDEX idx_account_number ON TRANSACTION(ACCOUNT_NUMBER);